
source 'https://rubygems.org'

gem 'rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'devise'
gem 'sqlite3'
gem 'spring'
gem 'paperclip', "~> 6.0.0"
gem 'knock'
gem 'savon', '~> 2.12.0'

group :doc do
	gem 'sdoc'
end